Update MERCHANT_INTEGRATION.md
solana-labs/solana-pay pull request #43
Opened 2022-02-02 05:45 UTC by vunderkind

There was a diff in the original SPL code that may be confusing for people who just want to copy the snippet and test out the SPL token transfer. I cleaned it up so it reads properly in JS.

2022-02-02 22:42 UTC, jordansexton commented
@cogoo would you review this?

2022-02-03 03:20 UTC, jordansexton requested changes
Thanks! If you merge from master into here, it should fix the one issue I commented on.

2022-02-03 03:20 UTC, jordansexton commented on docs/src/core/MERCHANT_INTEGRATION.md
> +    const splToken = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
This needs to be a pubkey, see https://github.com/solana-labs/solana-pay/pull/49

2022-02-03 03:22 UTC, merged

2022-02-03 09:38 UTC, vunderkind commented
Thanks everyone! 👍🏿